### ISSUE TITLE
手动集成SDK GizWifiSDK.framework加入后报错误Code sign error : bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by iOSPPP** [yaokantv/YKCenterDemo-iOS#1]
Code sign error : bundle format unrecognized, invalid, or unsuitable在手动添加GizWifiSDK.framework之后

**Comment by yaokantv** [comment]
你好，请参考最新的[文档 ](https://github.com/yaokantv/YKCenterDemo-iOS/blob/master/README.md)
